# Generated by Django 4.1.2 on 2022-10-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boma', '0002_profile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
    ]
