# Generated by Django 4.1.2 on 2022-11-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boma', '0003_alter_business_options_alter_neighbourhood_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='business',
            field=models.ManyToManyField(to='boma.business'),
        ),
    ]
